name: Test SNMP ARP Sync

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell: [bash, dash, zsh, ash]
      fail-fast: false
    name: Test with ${{ matrix.shell }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y snmp iproute2 gawk grep
    - name: "Install shell: ${{ matrix.shell }}"
      run: |
        case "${{ matrix.shell }}" in
          bash)
            sudo apt-get install -y bash
            ;;
          dash)
            sudo apt-get install -y dash
            ;;
          zsh)
            sudo apt-get install -y zsh
            ;;
          ash)
            sudo apt-get install -y busybox-static
            ;;
        esac
    - name: Ensure scripts are executable
      run: |
        chmod +x snmp-arp-sync.sh
        chmod +x test/test_ip_filter.sh
    - name: Run syntax check on main script
      run: |
        case "${{ matrix.shell }}" in
          bash)
            bash -n snmp-arp-sync.sh
            ;;
          dash)
            dash -n snmp-arp-sync.sh
            ;;
          zsh)
            zsh -n snmp-arp-sync.sh
            ;;
          ash)
            busybox ash -n snmp-arp-sync.sh
            ;;
        esac
    - name: Run test script with ${{ matrix.shell }}
      run: |
        case "${{ matrix.shell }}" in
          bash)
            bash test/test_ip_filter.sh
            ;;
          dash)
            dash test/test_ip_filter.sh
            ;;
          zsh)
            zsh test/test_ip_filter.sh
            ;;
          ash)
            busybox ash test/test_ip_filter.sh
            ;;
        esac
        
  integration-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y snmp iproute2 gawk grep
    - name: Make script executable
      run: chmod +x snmp-arp-sync.sh
    - name: Test argument validation
      run: |
        # Test missing required arguments
        if ./snmp-arp-sync.sh 2>/dev/null; then
          echo "Error: Script should have failed with missing arguments"
          exit 1
        else
          echo "Argument validation working correctly"
        fi
    - name: Test invalid arguments
      run: |
        # Test invalid option
        if ./snmp-arp-sync.sh --invalid-option 2>/dev/null; then
          echo "Error: Script should have failed with invalid option"
          exit 1
        else
          echo "Invalid option handling working correctly"
        fi
